name: Python pytest

on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest  # You can choose another OS if preferred

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace 'x' with the desired Python version, e.g., 3.6, 3.7, 3.8, etc.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have a requirements file, otherwise install pytest directly

    - name: Run pytest
      run: pytest  # Add any additional pytest options or arguments here if needed
